Updated tar file to include new script. Cleaned up the script.

diff --git a/bin/mountcifs b/bin/mountcifs
--- a/bin/mountcifs
+++ b/bin/mountcifs
@@ -1,5 +1,7 @@
 #!/bin/sh
 
+# Script to load/unload cifs/md4 modules and parse fstab file to mount
+# smb shares in chromeos developer mode.
 base_path=/usr/local
 
 load_modules() {
@@ -8,26 +10,25 @@ load_modules() {
   echo 0 > /sys/module/lsm/parameters/module_locking
 
   if [ x$( cat /proc/modules|grep -o cifs ) = "x" ]; then
-    /sbin/insmod $base_path/modules/cifs.ko || exit 1
+    /sbin/insmod $base_path/modules/cifs.ko && echo "Module cifs loaded" || exit 1
   fi
   if [ x$( cat /proc/modules|grep -o md4 ) = "x" ]; then
-    /sbin/insmod $base_path/modules/md4.ko || exit 1
+    /sbin/insmod $base_path/modules/md4.ko && echo "Module md4 loaded" || exit 1
   fi
 
   # Enable modules locking
   echo 1 > /sys/module/lsm/parameters/module_locking
   chmod 0400 /sys/module/lsm/parameters/module_locking
-  echo "Modules loaded"
 }
 
 unload_modules() {
   if [ x$( cat /proc/modules|grep -o cifs ) = "xcifs" ]; then
-    /sbin/rmmod cifs
+    /sbin/rmmod cifs && echo "Module cifs removed" || echo "Error removing cifs"
   fi
   if [ x$( cat /proc/modules|grep -o md4 ) = "xmd4" ]; then
-    /sbin/rmmod md4
+    /sbin/rmmod md4 && echo "Module md4 removed" || echo "Error removing md4"
   fi
-  echo "Modules removed"
+  
 }
 
 # In ../etc/fstab you can add your samba shares.
@@ -39,52 +40,53 @@ unload_modules() {
 #         mount your smb share. It doesn't work on ~/Downloads files won't be
 #         visible in the Files app from chromeos.
 mount_cifs() {
+  mount_case=$1
   cat $base_path/etc/fstab | while read line
     do
 
-      if [ "`echo x$line|grep -o '^x#'`" = 'x#' -o  "x$line" = 'x' ]; then   
+      if [ "$( echo x$line|grep -o '^x#' )" = 'x#' -o  "x$line" = 'x' ]; then   
         continue
       fi 
       mount_server=$(echo $line|cut -d ' ' -f1)
       mount_point=$(echo $line|cut -d ' ' -f2)
       mount_options=$(echo $line|cut -d ' ' -f4)
       if [ x$( cat /proc/mounts|cut -d ' ' -f2|grep -x $mount_point ) = x$mount_point ]; then
-        echo "$mount_point is already mounted"
+        if [ "$mount_case" -eq 1 ]; then
+          echo "$mount_point is already mounted"
+        else
+          umount "$mount_point" && \
+            echo "Unmounting $mount_point succesfull" || \
+            echo "Cannot unmount $mount_point"
+        fi
       else
-        mount -t cifs -o $mount_options $mount_server $mount_point && echo "Mounted $mount_server on $mount_point succesfull" || echo "Mount failed for $mount_server on $mount_point "
+        if [ "$mount_case" -eq 1 ]; then
+          mount -t cifs -o $mount_options $mount_server $mount_point && \
+            echo "Mounted $mount_server on $mount_point succesfull" || \
+            echo "Mount failed for $mount_server on $mount_point "
+        else
+          echo "$mount_server is not mounted on $mount_point"
+        fi
       fi
     done
 }
-# unmounts.
-umount_cifs() {
-  cat $base_path/etc/fstab | while read line
-    do
-      if [ "`echo x$line|grep -o '^x#'`" = 'x#' -o  "x$line" = 'x' ]; then
-        continue
-      fi 
-      mount_server=$(echo $line|cut -d ' ' -f1)
-      mount_point=$(echo $line|cut -d ' ' -f2)
-      if [ x$( cat /proc/mounts|cut -d ' ' -f2|grep -x $mount_point ) = x$mount_point ]; then  
-        umount "$mount_point" && echo "Unmounting $mount_point succesfull" || echo "Cannot unmount $mount_point"
-      else
-        echo "$mount_server is not mounted on $mount_point"        
-      fi 
-    done
-}
+
 # check if script is run as root
 uid=`id -u $USERNAME`
 if [ $uid -ne 0 ]; then
   echo "$0 must be run as root"
   exit 1
 fi
+# make sure /etc/fstab is only accesible by root, because
+# of the plain text credentials. In case the user forgets.
+chmod 0600 $base_path/etc/fstab
 
 case "$1" in
   start)
     load_modules
-    mount_cifs
+    mount_cifs 1
     ;;
   stop)
-    umount_cifs
+    mount_cifs 0
     sleep 1
     unload_modules
     ;;
